
from constants import (
    CHANNEL_API,
    CHANNEL_SESSION,
    CHANNEL_INTERNAL,
    CHECK_PLATFROM,
    ADMIN_ROLES,
    ALL_PLATFORMS,
    ACTION_VDI_DESCRIBE_POLICY_GROUPS,
    ACTION_VDI_CREATE_POLICY_GROUP,
    ACTION_VDI_MODIFY_POLICY_GROUP_ATTRIBUTES,
    ACTION_VDI_DELETE_POLICY_GROUPS,
    ACTION_VDI_ADD_RESOURCE_TO_POLICY_GROUP,
    ACTION_VDI_REMOVE_RESOURCE_FROM_POLICY_GROUP,
    ACTION_VDI_ADD_POLICY_TO_POLICY_GROUP,
    ACTION_VDI_REMOVE_POLICY_FROM_POLICY_GROUP,
    ACTION_VDI_APPLY_POLICY_GROUP,
    ACTION_VDI_MODIFY_RESOURCE_GROUP_POLICY,
)

POLICCY_GROUP_API_ACL = {
              ACTION_VDI_DESCRIBE_POLICY_GROUPS: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_CREATE_POLICY_GROUP: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_MODIFY_POLICY_GROUP_ATTRIBUTES: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_DELETE_POLICY_GROUPS: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_ADD_RESOURCE_TO_POLICY_GROUP: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_REMOVE_RESOURCE_FROM_POLICY_GROUP: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_ADD_POLICY_TO_POLICY_GROUP: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_REMOVE_POLICY_FROM_POLICY_GROUP: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_APPLY_POLICY_GROUP: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_MODIFY_RESOURCE_GROUP_POLICY: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },

              }