
from constants import (
    CHANNEL_API,
    CHANNEL_SESSION,
    CHANNEL_INTERNAL,
    CHECK_PLATFROM,
    ALL_PLATFORMS,
    USER_ROLE_GLOBAL_ADMIN,
    PLATFROM_CITRIX,
    ALL_ROLES,
    ACTION_VDI_DESCRIBE_DESKTOP_ZONES,
    ACTION_VDI_REFRESH_DESKTOP_ZONES,
    ACTION_VDI_CREATE_DESKTOP_ZONE,
    ACTION_VDI_MODIFY_DESKTOP_ZONE_ATTRIBUTES,
    ACTION_VDI_DELETE_DESKTOP_ZONES,
    ACTION_VDI_MODIFY_DESKTOP_ZONE_RESOURCE_LIMIT,
    ACTION_VDI_MODIFY_DESKTOP_ZONE_CONNECTION,
    ACTION_VDI_MODIFY_DESKTOP_ZONE_CITRIX_CONNECTION,
    ACTION_VDI_DESCRIBE_INSTANCE_CLASS_DISK_TYPE,
    ACTION_VDI_DESCRIBE_GPU_CLASS_TYPE,
    ACTION_VDI_CHECK_NETWORK_CONNECTION,
    ACTION_VDI_CHECK_GPU_CONFIG
)

ZONE_API_ACL = {
              ACTION_VDI_DESCRIBE_DESKTOP_ZONES: {
                  CHANNEL_API: ALL_ROLES,
                  CHANNEL_SESSION: ALL_ROLES,
                  CHANNEL_INTERNAL: ALL_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_REFRESH_DESKTOP_ZONES: {
                  CHANNEL_API: [USER_ROLE_GLOBAL_ADMIN],
                  CHANNEL_SESSION: [USER_ROLE_GLOBAL_ADMIN],
                  CHANNEL_INTERNAL: [USER_ROLE_GLOBAL_ADMIN],
                  CHECK_PLATFROM: ALL_PLATFORMS
              },
              ACTION_VDI_CREATE_DESKTOP_ZONE: {
                  CHANNEL_API: [USER_ROLE_GLOBAL_ADMIN],
                  CHANNEL_SESSION: [USER_ROLE_GLOBAL_ADMIN],
                  CHANNEL_INTERNAL: [USER_ROLE_GLOBAL_ADMIN],
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_MODIFY_DESKTOP_ZONE_ATTRIBUTES: {
                  CHANNEL_API: [USER_ROLE_GLOBAL_ADMIN],
                  CHANNEL_SESSION: [USER_ROLE_GLOBAL_ADMIN],
                  CHANNEL_INTERNAL: [USER_ROLE_GLOBAL_ADMIN],
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_DELETE_DESKTOP_ZONES: {
                  CHANNEL_API: [USER_ROLE_GLOBAL_ADMIN],
                  CHANNEL_SESSION: [USER_ROLE_GLOBAL_ADMIN],
                  CHANNEL_INTERNAL: [USER_ROLE_GLOBAL_ADMIN],
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_MODIFY_DESKTOP_ZONE_RESOURCE_LIMIT: {
                  CHANNEL_API: [USER_ROLE_GLOBAL_ADMIN],
                  CHANNEL_SESSION: [USER_ROLE_GLOBAL_ADMIN],
                  CHANNEL_INTERNAL: [USER_ROLE_GLOBAL_ADMIN],
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_MODIFY_DESKTOP_ZONE_CONNECTION: {
                  CHANNEL_API: [USER_ROLE_GLOBAL_ADMIN],
                  CHANNEL_SESSION: [USER_ROLE_GLOBAL_ADMIN],
                  CHANNEL_INTERNAL: [USER_ROLE_GLOBAL_ADMIN],
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_MODIFY_DESKTOP_ZONE_CITRIX_CONNECTION: {
                  CHANNEL_API: [USER_ROLE_GLOBAL_ADMIN],
                  CHANNEL_SESSION: [USER_ROLE_GLOBAL_ADMIN],
                  CHANNEL_INTERNAL: [USER_ROLE_GLOBAL_ADMIN],
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
            ACTION_VDI_DESCRIBE_INSTANCE_CLASS_DISK_TYPE: {
                CHANNEL_API: ALL_ROLES,
                CHANNEL_SESSION: ALL_ROLES,
                CHANNEL_INTERNAL: ALL_ROLES,
                CHECK_PLATFROM: ALL_PLATFORMS
                },
            ACTION_VDI_DESCRIBE_GPU_CLASS_TYPE: {
                CHANNEL_API: ALL_ROLES,
                CHANNEL_SESSION: ALL_ROLES,
                CHANNEL_INTERNAL: ALL_ROLES,
                CHECK_PLATFROM: ALL_PLATFORMS
                },
            ACTION_VDI_CHECK_NETWORK_CONNECTION: {
                CHANNEL_API: ALL_ROLES,
                CHANNEL_SESSION: ALL_ROLES,
                CHANNEL_INTERNAL: ALL_ROLES,
                CHECK_PLATFROM: ALL_PLATFORMS
                },
            ACTION_VDI_CHECK_GPU_CONFIG: {
                CHANNEL_API: ALL_ROLES,
                CHANNEL_SESSION: ALL_ROLES,
                CHANNEL_INTERNAL: ALL_ROLES,
                CHECK_PLATFROM: ALL_PLATFORMS
                }
              }