
ACTION_DESCRIBE_COMPUTER_CATALOGS = "DescribeComputerCatalogs"
ACTION_CREATE_COMPUTER_CATALOG = "CreateComputerCatalog"
ACTION_MODIFY_COMPUTER_CATALOG = "ModifyComputerCatalog"
ACTION_DELETE_COMPUTER_CATALOG = "DeleteComputerCatalog"
ACTION_UPDATE_CATALOG_MASTER_IMAGE = "UpdateCatalogMasterImage"

ACTION_DESCRIBE_DELIVERY_GROUPS = "DescribeDeliveryGroups"
ACTION_CREATE_DELIVERY_GROUP = "CreateDeliveryGroup"
ACTION_MODIFY_DELIVERY_GROUP = "ModifyDeliveryGroup"
ACTION_DELETE_DELIVERY_GROUP = "DeleteDeliveryGroup"
ACTION_ATTACH_COMPUTER_TO_DELIVERY_GROUP = "AttachComputerToDeliveryGroup"
ACTION_DETACH_COMPUTER_FROM_DELIVERY_GROUP = "DetachComputerFromDeliveryGroup"
ACTION_ATTACH_USER_TO_DELIVERY_GROUP = "AttachUserToDeliveryGroup"
ACTION_DETACH_USER_FROM_DELIVERY_GROUP = "DetachUserFromDeliveryGroup"
ACTION_RESET_USER_TO_DELIVERY_GROUP = "ResetUsersToDeliveryGroup"
ACTION_SET_DELIVERY_GROUP_MODE ="SetDeliveryGroupMode"
ACTION_SET_COMPUTER_MODE ="SetComputerMode"

ACTION_DESCRIBE_COMPUTERS = "DescribeComputers"
ACTION_CREATE_COMPUTER = "CreateComputer"
ACTION_DELETE_COMPUTER = "DeleteComputer"
ACTION_START_COMPUTER = "StartComputer"
ACTION_STOP_COMPUTER = "StopComputer"
ACTION_RESTART_COMPUTER = "RestartComputer"
ACTION_ATTACH_COMPUTER_TO_USER = "AttachComputerToUser"
ACTION_DETACH_COMPUTER_FROM_USER = "DetachComputerFromUser"
ACTION_STOP_BROKER_SESSION = "StopBrokerSession"

# app
ACTION_ADD_COMPUTER = "AddComputer"
ACTION_DELETE_APP_COMPUTER = "DeleteAppComputer"
ACTION_DESCRIBE_APP_STARTMEMU = "DescribeAppStartMenu"
ACTION_CREATE_BROKER_APP = "CreateBrokerApp"
ACTION_ADD_BROKER_APP = "AddBrokerApp"
ACTION_MODIFY_BROKER_APP = "ModifyBrokerApp"
ACTION_REMOVE_BROKER_APP = "RemoveBrokerApp"
ACTION_DESCRIBE_BROKER_APPS = "DescribeBrokerApps"
ACTION_NEW_BROKER_FOLDER = "NewBrokerFolder"
ACTION_REMOVE_BROKER_FOLDER = "RemoveBrokerFolder"
ACTION_DESCRIBE_BROKER_FOLDER = "DescribeBrokerFolder"
ACTION_DESCRIBE_BROKER_APP_GROUPS = "DescribeBrokerAppGroups"
ACTION_ADD_BROKER_APP_GROUP = "AddBrokerAppGroup"
ACTOPN_CREATE_BROKER_APP_GROUP = "CreateBrokerAppGroup"
ACTOPN_DELETE_BROKER_APP_GROUP = "RemoveBrokerAppGroup"

ACTION_DESCRIBE_JOBS = "DescribeJobs"
ACTION_RELOAD_IMAGE = "ReloadImage"

ACTION_CREATE_CITRIX_POLICY = "CreateCitrixPolicy"
ACTION_CONFIG_CITRIX_POLICY_ITEM = "ConfigCitrixPolicyItem"
ACTION_DESCRIBE_CITRIX_POLICY = "DescribeCitrixPolicy"
ACTION_DESCRIBE_CITRIX_POLICY_ITEM = "DescribeCitrixPolicyItem"
ACTION_DESCRIBE_CITRIX_POLICY_CONFIG = "DescribeCitrixPolicyConfig"
ACTION_DELETE_CITRIX_POLICY = "DeleteCitrixPolicy"
ACTION_MODIFY_CITRIX_POLICY = "ModifyCitrixPolicy"
ACTION_RENAME_CITRIX_POLICY = "RenameCitrixPolicy"
ACTION_SET_CITRIX_POLICY_PRIORITY="SetCitrixPolicyPriority"
ACTION_DESCRIBE_CITRIX_POLICY_FILTER="DescribeCitrixPolicyFilter"
ACTION_ADD_CITRIX_POLICY_FILTER="AddCitrixPolicyFilter"
ACTION_MODIFY_CITRIX_POLICY_FILTER="ModifyCitrixPolicyFilter"
ACTION_DELETE_CITRIX_POLICY_FILTER="DeleteCitrixPolicyFilter"
# job action
JOB_ACTIONS =[
    ACTION_CREATE_COMPUTER_CATALOG,
    ACTION_MODIFY_COMPUTER_CATALOG,
    ACTION_DELETE_COMPUTER_CATALOG,
    ACTION_CREATE_COMPUTER,
    ACTION_DELETE_COMPUTER,
    ACTION_START_COMPUTER,
    ACTION_STOP_COMPUTER,
    ACTION_RESTART_COMPUTER,    
]

NO_JOB_RES = "no_job"

RETRY_ACTIONS = [
    ACTION_DESCRIBE_COMPUTER_CATALOGS,
    ACTION_DESCRIBE_DELIVERY_GROUPS
    
]

DG_STATUS_MAINT = "maint"
DG_STATUS_NORMAL = "normal"

# resource job interval
JOB_INTERVAL_10S = 10
JOB_INTERVAL_5S = 5
JOB_INTERVAL_3S = 3
JOB_INTERVAL_60S = 60
# retry time
RES_ACTION_RETRIES = 6
RES_ACTION_RETRY_INTERVAL = 5
# job timeout
CHECK_JOB_INTERVAL = 3
WAIT_JOB_TIMEOUT = 1800
QC_RESOURCE_JOB_LOCK='qc_resource_job'
