
from constants import (
    CHANNEL_API,
    CHANNEL_SESSION,
    CHANNEL_INTERNAL,
    CHECK_PLATFROM,
    ALL_PLATFORMS,

    ACTION_VDI_DESCRIBE_DESKTOP_SECURITY_POLICYS,
    ACTION_VDI_CREATE_DESKTOP_SECURITY_POLICY,
    ACTION_VDI_MODIFY_DESKTOP_SECURITY_POLICY_ATTRIBUTES,
    ACTION_VDI_DELETE_DESKTOP_SECURITY_POLICYS,
    ACTION_VDI_APPLY_DESKTOP_SECURITY_POLICY,
    
    ACTION_VDI_DESCRIBE_DESKTOP_SECURITY_RULES,
    ACTION_VDI_ADD_DESKTOP_SECURITY_RULES,
    ACTION_VDI_REMOVE_DESKTOP_SECURITY_RULES,
    ACTION_VDI_MODIFY_DESKTOP_SECURITY_RULE_ATTRIBUTES,
    
    ACTION_VDI_DESCRIBE_DESKTOP_SECURITY_IPSETS,
    ACTION_VDI_CREATE_DESKTOP_SECURITY_IPSET,
    ACTION_VDI_DELETE_DESKTOP_SECURITY_IPSETS,
    ACTION_VDI_MODIFY_DESKTOP_SECURITY_IPSET_ATTRIBUTES,
    ACTION_VDI_DESCRIBE_SYSTEM_SECURITY_POLICYS,
    ACTION_VDI_DESCRIBE_SYSTEM_SECURITY_IPSETS,
    ACTION_VDI_APPLY_DESKTOP_SECURITY_IPSET,

    ACTION_VDI_LOAD_SYSTEM_SECURITY_RULES,
    ACTION_VDI_LOAD_SYSTEM_SECURITY_IPSETS,

)

from constants import (
    ADMIN_ROLES
)

SECURITY_POLICY_API_ACL = {
              ACTION_VDI_DESCRIBE_DESKTOP_SECURITY_POLICYS: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_CREATE_DESKTOP_SECURITY_POLICY: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_MODIFY_DESKTOP_SECURITY_POLICY_ATTRIBUTES: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_DELETE_DESKTOP_SECURITY_POLICYS: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_APPLY_DESKTOP_SECURITY_POLICY: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_DESCRIBE_DESKTOP_SECURITY_RULES: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_ADD_DESKTOP_SECURITY_RULES: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_REMOVE_DESKTOP_SECURITY_RULES: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_MODIFY_DESKTOP_SECURITY_RULE_ATTRIBUTES: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_DESCRIBE_DESKTOP_SECURITY_IPSETS: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_CREATE_DESKTOP_SECURITY_IPSET: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_DELETE_DESKTOP_SECURITY_IPSETS: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_MODIFY_DESKTOP_SECURITY_IPSET_ATTRIBUTES: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_APPLY_DESKTOP_SECURITY_IPSET: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_DESCRIBE_SYSTEM_SECURITY_POLICYS: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_DESCRIBE_SYSTEM_SECURITY_IPSETS: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_LOAD_SYSTEM_SECURITY_RULES: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
              ACTION_VDI_LOAD_SYSTEM_SECURITY_IPSETS: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },

              }