
from constants import (
    CHANNEL_API,
    CHANNEL_SESSION,
    CHANNEL_INTERNAL,
    CHECK_PLATFROM,
    ALL_PLATFORMS,
    USER_ROLE_GLOBAL_ADMIN,

    # system custom
    ACTION_VDI_DESCRIBE_SYSTEM_CUSTOM_CONFIGS,
    ACTION_VDI_MODIFY_SYSTEM_CUSTOM_CONFIG_ATTRIBUTES,
    ACTION_VDI_RESET_SYSTEM_CUSTOM_CONFIGS

)

from constants import (
    ADMIN_ROLES,
    ALL_ROLES
)

SYSTEM_CUSTOM_API_ACL = {
        ACTION_VDI_DESCRIBE_SYSTEM_CUSTOM_CONFIGS: {
            CHANNEL_API: ALL_ROLES,
            CHANNEL_SESSION: ALL_ROLES,
            CHANNEL_INTERNAL: ALL_ROLES,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_MODIFY_SYSTEM_CUSTOM_CONFIG_ATTRIBUTES: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
        },
        ACTION_VDI_RESET_SYSTEM_CUSTOM_CONFIGS: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
        }
    }