
from constants import (
    CHANNEL_API,
    CHANNEL_SESSION,
    CHANNEL_INTERNAL,
    CHECK_PLATFROM,
    ALL_PLATFORMS,
    USER_ROLE_GLOBAL_ADMIN,

    # file_share
    ACTION_VDI_DESCRIBE_FILE_SHARE_GROUPS,
    ACTION_VDI_CREATE_FILE_SHARE_GROUP,
    ACTION_VDI_MODIFY_FILE_SHARE_GROUP_ATTRIBUTES,
    ACTION_VDI_RENAME_FILE_SHARE_GROUP,
    ACTION_VDI_DELETE_FILE_SHARE_GROUPS,
    ACTION_VDI_MODIFY_FILE_SHARE_GROUP_ZONE_USER,

    ACTION_VDI_DESCRIBE_FILE_SHARE_GROUP_FILES,
    ACTION_VDI_UPLOAD_FILE_SHARE_GROUP_FILES,
    ACTION_VDI_DOWNLOAD_FILE_SHARE_GROUP_FILES,
    ACTION_VDI_MODIFY_FILE_SHARE_GROUP_FILE_ATTRIBUTES,
    ACTION_VDI_DELETE_FILE_SHARE_GROUP_FILES,
    ACTION_VDI_DESCRIBE_FILE_SHARE_GROUP_FILE_DOWNLOAD_HISTORY,

    ACTION_VDI_DESCRIBE_FILE_SHARE_CAPACITY,
    ACTION_VDI_CHANGE_FILE_IN_FILE_SHARE_GROUP,
    ACTION_VDI_DESCRIBE_FILE_SHARE_RECYCLES,
    ACTION_VDI_RESTORE_FILE_SHARE_RECYCLES,
    ACTION_VDI_DELETE_PERMANENTLY_FILE_SHARE_RECYCLES,
    ACTION_VDI_EMPTY_FILE_SHARE_RECYCLES,

    ACTION_VDI_CREATE_FILE_SHARE_SERVICE,
    ACTION_VDI_LOAD_FILE_SHARE_SERVICE,
    ACTION_VDI_DESCRIBE_FILE_SHARE_SERVICES,
    ACTION_VDI_MODIFY_FILE_SHARE_SERVICE_ATTRIBUTES,
    ACTION_VDI_DELETE_FILE_SHARE_SERVICES,
    ACTION_VDI_REFRESH_FILE_SHARE_SERVICE,
    ACTION_VDI_DESCRIBE_FILE_SHARE_SERVICE_VNAS,
    ACTION_VDI_RESET_FILE_SHARE_SERVICE_PASSWORD,
)

from constants import (
    ADMIN_ROLES,
    ALL_ROLES
)

FILE_SHARE_API_ACL = {
            ACTION_VDI_DESCRIBE_FILE_SHARE_GROUPS: {
                  CHANNEL_API: ALL_ROLES,
                  CHANNEL_SESSION: ALL_ROLES,
                  CHANNEL_INTERNAL: ALL_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
            ACTION_VDI_CREATE_FILE_SHARE_GROUP: {
                  CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                  CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                  CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
            ACTION_VDI_MODIFY_FILE_SHARE_GROUP_ATTRIBUTES: {
                  CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                  CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                  CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
            ACTION_VDI_RENAME_FILE_SHARE_GROUP: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_DELETE_FILE_SHARE_GROUPS: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_MODIFY_FILE_SHARE_GROUP_ZONE_USER: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_DESCRIBE_FILE_SHARE_GROUP_FILES: {
                CHANNEL_API: ALL_ROLES,
                CHANNEL_SESSION: ALL_ROLES,
                CHANNEL_INTERNAL: ALL_ROLES,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_UPLOAD_FILE_SHARE_GROUP_FILES: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_DOWNLOAD_FILE_SHARE_GROUP_FILES: {
                CHANNEL_API: ALL_ROLES,
                CHANNEL_SESSION: ALL_ROLES,
                CHANNEL_INTERNAL: ALL_ROLES,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_MODIFY_FILE_SHARE_GROUP_FILE_ATTRIBUTES: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_DELETE_FILE_SHARE_GROUP_FILES: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_DESCRIBE_FILE_SHARE_GROUP_FILE_DOWNLOAD_HISTORY: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_DESCRIBE_FILE_SHARE_CAPACITY: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_CHANGE_FILE_IN_FILE_SHARE_GROUP: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_DESCRIBE_FILE_SHARE_RECYCLES: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_RESTORE_FILE_SHARE_RECYCLES: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_DELETE_PERMANENTLY_FILE_SHARE_RECYCLES: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_EMPTY_FILE_SHARE_RECYCLES: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_CREATE_FILE_SHARE_SERVICE: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_LOAD_FILE_SHARE_SERVICE: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_DESCRIBE_FILE_SHARE_SERVICES: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_MODIFY_FILE_SHARE_SERVICE_ATTRIBUTES: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_DELETE_FILE_SHARE_SERVICES: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_REFRESH_FILE_SHARE_SERVICE: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_DESCRIBE_FILE_SHARE_SERVICE_VNAS: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_RESET_FILE_SHARE_SERVICE_PASSWORD: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
        }