
from constants import (
    CHANNEL_API,
    CHANNEL_SESSION,
    CHANNEL_INTERNAL,
    CHECK_PLATFROM,
    PLATFROM_CITRIX,

    ACTION_VDI_DESCRIBE_DELIVERY_GROUPS,
    ACTION_VDI_CREATE_DELIVERY_GROUP,
    ACTION_VDI_MODIFY_DELIVERY_GROUP_ATTRIBUTES,
    ACTION_VDI_DELETE_DELIVERY_GROUPS,
    ACTION_VDI_LOAD_DELIVERY_GROUPS,
    ACTION_VDI_ADD_DESKTOP_TO_DELIVERY_GROUP,
    ACTION_VDI_DEL_DESKTOP_FROM_DELIVERY_GROUP,
    ACTION_VDI_ADD_USER_TO_DELIVERY_GROUP,
    ACTION_VDI_DEL_USER_FROM_DELIVERY_GROUP,
    ACTION_VDI_ATTACH_DESKTOP_TO_DELIVERY_GROUP_USER,
    ACTION_VDI_DETACH_DESKTOP_FROM_DELIVERY_GROUP_USER,
    ACTION_VDI_SET_DELIVERY_GROUP_MODE,
    ACTION_VDI_SET_CITRIX_DESKTOP_MODE,
    ACTION_VDI_DESCRIBE_COMPUTER_CATALOGS,
    ACTION_VDI_LOAD_COMPUTER_CATALOGS,
    ACTION_VDI_DESCRIBE_COMPUTERS,
    ACTION_VDI_LOAD_COMPUTERS,
    ACTION_VDI_REFRESH_CITRIX_DESKTOPS,
)

from constants import (
    ADMIN_ROLES
)

CITRIX_API_ACL = {
            ACTION_VDI_DESCRIBE_DELIVERY_GROUPS: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: PLATFROM_CITRIX
             },
            ACTION_VDI_CREATE_DELIVERY_GROUP: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: PLATFROM_CITRIX
             },
            ACTION_VDI_MODIFY_DELIVERY_GROUP_ATTRIBUTES: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: PLATFROM_CITRIX
             },
            ACTION_VDI_DELETE_DELIVERY_GROUPS: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: PLATFROM_CITRIX
             },
            ACTION_VDI_LOAD_DELIVERY_GROUPS: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: PLATFROM_CITRIX
             },
            ACTION_VDI_ADD_DESKTOP_TO_DELIVERY_GROUP: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: PLATFROM_CITRIX
             },
            ACTION_VDI_DEL_DESKTOP_FROM_DELIVERY_GROUP: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: PLATFROM_CITRIX
             },
            ACTION_VDI_ADD_USER_TO_DELIVERY_GROUP: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: PLATFROM_CITRIX
             },
            ACTION_VDI_DEL_USER_FROM_DELIVERY_GROUP: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: PLATFROM_CITRIX
             },
            ACTION_VDI_ATTACH_DESKTOP_TO_DELIVERY_GROUP_USER: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: PLATFROM_CITRIX
             },
            ACTION_VDI_DETACH_DESKTOP_FROM_DELIVERY_GROUP_USER: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: PLATFROM_CITRIX
             },
            ACTION_VDI_SET_DELIVERY_GROUP_MODE: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: PLATFROM_CITRIX
             },
            ACTION_VDI_SET_CITRIX_DESKTOP_MODE: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: PLATFROM_CITRIX
             },
            ACTION_VDI_DESCRIBE_COMPUTER_CATALOGS: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: PLATFROM_CITRIX
             },
            ACTION_VDI_LOAD_COMPUTER_CATALOGS: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: PLATFROM_CITRIX
             },
            ACTION_VDI_DESCRIBE_COMPUTERS: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: PLATFROM_CITRIX
             },
            ACTION_VDI_LOAD_COMPUTERS: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: PLATFROM_CITRIX
             },
            ACTION_VDI_REFRESH_CITRIX_DESKTOPS: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: PLATFROM_CITRIX
             },
        }