
from constants import (
    CHANNEL_API,
    CHANNEL_SESSION,
    CHANNEL_INTERNAL,
    CHECK_PLATFROM,
    ALL_PLATFORMS,
    USER_ROLE_GLOBAL_ADMIN,

    # terminal management
    ACTION_VDI_DESCRIBE_TERMINAL_MANAGEMENTS,
    ACTION_VDI_MODIFY_TERMINAL_MANAGEMENT_ATTRIBUTES,
    ACTION_VDI_DELETE_TERMINAL_MANAGEMENTS,
    ACTION_VDI_RESTART_TERMINALS,
    ACTION_VDI_STOP_TERMINALS,

    ACTION_VDI_DESCRIBE_TERMINAL_GROUPS,
    ACTION_VDI_CREATE_TERMINAL_GROUP,
    ACTION_VDI_MODIFY_TERMINAL_GROUP_ATTRIBUTES,
    ACTION_VDI_DELETE_TERMINAL_GROUPS,
    ACTION_VDI_ADD_TERMINAL_TO_TERMINAL_GROUP,
    ACTION_VDI_DELETE_TERMINAL_FROM_TERMINAL_GROUP,

    ACTION_VDI_DESCRIBE_MASTER_BACKUP_IPS,
    ACTION_VDI_DESCRIBE_CBSERVER_HOSTS
)

from constants import (
    ADMIN_ROLES,
    ALL_ROLES
)

TERMINAL_API_ACL = {
            ACTION_VDI_DESCRIBE_TERMINAL_MANAGEMENTS: {
                  CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                  CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                  CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
            ACTION_VDI_MODIFY_TERMINAL_MANAGEMENT_ATTRIBUTES: {
                  CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                  CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                  CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
            ACTION_VDI_DELETE_TERMINAL_MANAGEMENTS: {
                  CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                  CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                  CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
            ACTION_VDI_RESTART_TERMINALS: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
                },
            ACTION_VDI_STOP_TERMINALS: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
                },
            ACTION_VDI_DESCRIBE_TERMINAL_GROUPS: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_CREATE_TERMINAL_GROUP: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_MODIFY_TERMINAL_GROUP_ATTRIBUTES: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_DELETE_TERMINAL_GROUPS: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_ADD_TERMINAL_TO_TERMINAL_GROUP: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_DELETE_TERMINAL_FROM_TERMINAL_GROUP: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_DESCRIBE_MASTER_BACKUP_IPS: {
                CHANNEL_API: ALL_ROLES,
                CHANNEL_SESSION: ALL_ROLES,
                CHANNEL_INTERNAL: ALL_ROLES,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_DESCRIBE_CBSERVER_HOSTS: {
                CHANNEL_API: ALL_ROLES,
                CHANNEL_SESSION: ALL_ROLES,
                CHANNEL_INTERNAL: ALL_ROLES,
                CHECK_PLATFROM: ALL_PLATFORMS
            }
        }