
from constants import (
    CHANNEL_API,
    CHANNEL_SESSION,
    CHANNEL_INTERNAL,
    CHECK_PLATFROM,
    ALL_PLATFORMS,
    USER_ROLE_GLOBAL_ADMIN,

    # module_custom
    ACTION_VDI_DESCRIBE_USER_MODULE_CUSTOMS,
    ACTION_VDI_CREATE_USER_MODULE_CUSTOM,
    ACTION_VDI_MODIFY_USER_MODULE_CUSTOM_ATTRIBUTES,
    ACTION_VDI_MODIFY_USER_MODULE_CUSTOM_CONFIGS,
    ACTION_VDI_MODIFY_USER_MODULE_CUSTOM_ZONE_USER,
    ACTION_VDI_DELETE_USER_MODULE_CUSTOMS,
    ACTION_VDI_DESCRIBE_SYSTEM_MODULE_TYPES
)

from constants import (
    ADMIN_ROLES,
    ALL_ROLES
)

MODULE_CUSTOM_API_ACL = {
            ACTION_VDI_DESCRIBE_USER_MODULE_CUSTOMS: {
                    CHANNEL_API: ADMIN_ROLES,
                    CHANNEL_SESSION: ADMIN_ROLES,
                    CHANNEL_INTERNAL: ADMIN_ROLES,
                    CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_CREATE_USER_MODULE_CUSTOM: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_MODIFY_USER_MODULE_CUSTOM_ATTRIBUTES: {
                    CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                    CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                    CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                    CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_MODIFY_USER_MODULE_CUSTOM_CONFIGS: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_MODIFY_USER_MODULE_CUSTOM_ZONE_USER: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_DELETE_USER_MODULE_CUSTOMS: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_DESCRIBE_SYSTEM_MODULE_TYPES: {
                CHANNEL_API: ALL_ROLES,
                CHANNEL_SESSION: ALL_ROLES,
                CHANNEL_INTERNAL: ALL_ROLES,
                CHECK_PLATFROM: ALL_PLATFORMS
                },
        }