'''
Created on 2012-9-10

@author: yunify
'''

'''
    Here are the definition of error codes.
'''
#----------------------------------------
# Client Error Codes
#----------------------------------------

NEED_UPDATE_DESKTOP_STATUS = 999
# request
INVALID_REQUEST_FORMAT = 1000
INVALID_REQUEST_METHOD = 1001
REQUEST_HAS_EXPIRED = 1002
INVALID_REQUEST_PARAM_VALUE = 1003
SESSION_EXPIRED = 1005
INVALID_API_MODULES = 1006

USER_NAME_ERROR = 1007
INVALID_REQUEST_FORMAT_SK = 1008

# user
PERMISSION_DENIED = 2000
AUTH_FAILURE = 2001
USER_ALREADY_EXISTED = 2002
INVALID_USER_ID = 2003
LOGIN_FAILED = 2004
USER_NOT_FOUND = 2005
PASSWD_NOT_MATCHED = 2006
RESET_PASSWD_FAILED = 2007
USER_OR_PASSWD_NOT_MATCHED = 2008
DELETE_USER_ERROR = 2009
INSERT_USER_SCOPE_ERROR = 2010
CLEAR_USER_SCOPE_ERROR = 2011
INVALID_EMAIL_ADDR = 2012
DESCRIBE_USER_SCOPE_ERROR = 2013
MODIFY_USER_SCOPE_ERROR = 2014
ENABLE_DESKTOP_USER_ERROR = 2015
DISABLE_DESKTOP_USER_ERROR = 2016
MODIFY_DESKTOP_USER_ROLE_ERROR = 2017
USER_GROUP_NOT_EXISTED = 2018
MODIGY_USER_ERROR = 2019
CREATE_USER_GROUP_ERROR = 2018
MODIGY_USER_GROUP_ERROR = 2020
DELETE_USER_GROUP_ERROR = 2021
DESCRIBE_USER_GROUP_ERROR = 2021
CHANGE_USER_IN_GROUP_ERROR = 2022
USER_NOT_IN_GROUP_ERROR = 2022
USER_GROUP_HAVE_SUB_USER_GROUPS = 2023
USER_GROUP_HAVE_SUB_USERS = 2024
CLEAR_RESOURCES_ERROR = 2025
ADD_SYSTEM_LOG_ERROR = 2026
GET_SYSTEM_LOG_ERROR = 2027
CREATE_USER_ERROR = 2028
DESCRIBE_USER_ERROR = 2028
CREATE_APPLY_FORM_ERROR = 2029
DELETE_APPLY_FORM_ERROR = 2030
DESCEIBE_APPLY_FORM_ERROR = 2031
APPLY_FORM_STATUS_ERROR = 2032
MODIFY_APPLY_FORM_ERROR = 2033
APPLY_FORM_NOT_EXISTED_ERROR = 2039
APPLY_FORM_PERMISSION_ERROR = 2040

#auth
CREATE_AUTH_ORGANIZATION_ERROR = 2041
DESCRIBE_AUTH_ORGANIZATIONS_ERROR = 2042
MODIFY_AUTH_ORGANIZATION_ERROR = 2043
DELETE_AUTH_ORGANIZATIONS_ERROR = 2044
CREATE_AUTH_USER_ERROR = 2045
DESCRIBE_AUTH_USERS_ERROR = 2046
MODIFY_AUTH_USER_ERROR = 2047
DELETE_AUTH_USERS_ERROR = 2048
MODIFY_AUTH_USER_PASSWORD_ERROR = 2049
CHANGE_AUTH_USER_IN_ORGANIZATION_ERROR = 2050
AUTH_SERVER_CONFIG_ERROR = 2051
#system config
MODIFY_SYSTEM_CONDIF_ERROR = 2052
DESCRIBE_SYSTEM_CONDIF_ERROR = 2053
SYSTEM_CONDIF_KEY_NOT_EXISTS_ERROR = 2054
#guest
SEND_GUEST_MESSAGE_ERROR = 2055
SEND_GUEST_HOT_KEYS_ERROR = 2056
#spice
CREATE_SPICE_CONN_FILE_ERROR = 2057

USER_NOT_EXISTED = 2058
USER_IS_NOT_ACTIVE = 2059


#desktop maintainer
DESKTOP_MAINTAINER_ERROR = 2058


# resource
RESOURCE_NOT_FOUND = 3001
RESOURCE_ALREADY_EXISTED = 3002
RESOURCES_DEPENDENCE = 3003

# apply group
CREATE_APPLY_GROUP_FORM_ERROR = 3004
MODIFY_APPLY_GROUP_FORM_ERROR = 3005
DELETE_APPLY_GROUP_FORM_ERROR = 3006
INSERT_APPLY_GROUP_USER_FORM_ERROR = 3007
REMOVE_APPLY_GROUP_USER_FORM_ERROR = 3008
INSERT_APPLY_GROUP_RESOURCE_FORM_ERROR = 3009
REMOVE_APPLY_GROUP_RESOURCE_FORM_ERROR = 3010

# approve group
CREATE_APPROVE_GROUP_FORM_ERROR = 3020
MODIFY_APPROVE_GROUP_FORM_ERROR = 3021
DELETE_APPROVE_GROUP_FORM_ERROR = 3022
INSERT_APPROVE_GROUP_USER_FORM_ERROR = 3023
REMOVE_APPROVE_GROUP_USER_FORM_ERROR = 3024
MAP_APPLY_GROUP_AND_APPROVE_GROUP_ERROR = 3025
UNMAP_APPLY_GROUP_AND_APPROVE_GROUP_ERROR = 3026

# component version
DESCRIBE_COMPONENT_VERSION_ERROR = 3030
UPDATE_COMPONENT_VERSION_ERROR = 3031

# file share
LOAD_FTP_FILE_SHARE_SERVICE_ERROR = 3032


#----------------------------------------
# Iaas Error Codes
#----------------------------------------
IAAS_API_ERROR = 4000

#----------------------------------------
# Server Error Codes
#----------------------------------------

#server
INTERNAL_ERROR = 5000
SERVER_BUSY = 5001
INSUFFICIENT_RESOURCES = 5002
SERVERS_UPDATING = 5003
SERVICE_ABNORMAL = 5010
# database
DATABASE_OPERATION_EXCEPTION = 5100
# ad server
AUTH_SERVER_OPERATION_EXCEPTION = 5101
AUHT_SERVICE_CONFIG_ERROR = 5102

# ldap
LDAP_MODIFY_S_SUCCESS = 103
LDAP_ADD_S_SUCCESS = 105
LDAP_DELETE_S_SUCCESS = 107

#----------------------------------------
# Push Server Error Codes
#----------------------------------------
PUSH_SERVER_INTERNAL_ERROR = 6000
PUSH_SERVER_URI_ERROR = 6001
PUSH_SERVER_REQUEST_PARAMS_ERROR = 6002
PUSH_SERVER_REQUEST_SESSION_ERROR = 6003
PUSH_SERVER_WEBSOCKET_SUBSCRIBE_ERROR = 6004
PUSH_SERVER_WEBSOCKET_UNSUBSCRIBE_ERROR = 6005

#----------------------------------------
# VDHost Server Error Codes
#----------------------------------------
VDHOST_SERVER_INTERNAL_ERROR = 7000
VDHOST_NOT_FOUND = 7001


#----------------------------------------
# Storefront Error Codes
#----------------------------------------
STOREFRONT_INTERNAL_ERROR = 9000
STOREFRONT_LOGIN_ERROR = 9001
STOREFRONT_GETDESKTOPLIST_UNAUTHORIZE_ERROR = 9002
STOREFRONT_GETDESKTOPLIST_ERROR = 9003
STOREFRONT_GETDESKTOPLIST_NODESKTOP_ERROR = 9004
STOREFRONT_NOTFOUND_ICA_ERROR = 9005
STOREFRONT_DOWNLOAD_ICA_ERROR = 9006
STOREFRONT_ASSIGN_DESKTOP_ERROR = 9007
STOREFRONT_TOKEN_MISSING_ERROR = 9008
STOREFRONT_DLV_NAME_ERROR = 9009
STOREFRONT_CONNECTION_ERROR = 9010
STOREFRONT_GET_STATUS_ICA_ERROR = 9011
#----------------------------------------
# Radius Error Codes
#----------------------------------------
RADIUS_INTERNAL_ERROR = 10000
RADIUS_DATABASE_ERROR = 10001
RADIUS_CONNECT_CHECK_ERROR = 10002
RADIUS_CHECK_REJECT_ERROR = 10003
USER_EXCEDD_ERROR_TIMES = 10004
RADIUS_CHECK_OTHER_ERROR = 10005

# workflow

WF_SERVICE_TYPE_ENV_ERROR = 11001
WF_API_ACTION_PARAMS_ERROR = 11002

# AD
AUTH_SERVICE_IS_BUSY = 9500

#----------------------------------------
# terminal Server Error Codes
#----------------------------------------
TERMINAL_SERVER_INTERNAL_ERROR = 7100
