# gpu
ACTION_DESCRIBE_GPUS = "DescribeGPUs"
# jobs
ACTION_DESCRIBE_JOBS = "DescribeJobs"
# images
ACTION_DESCRIBE_IMAGES = "DescribeImages"
ACTION_CAPTURE_INSTANCE = "CaptureInstance"
ACTION_DELETE_IMAGES = "DeleteImages"
ACTION_MODIFY_IMAGE_ATTRIBUTES = "ModifyImageAttributes"
# instances
ACTION_DESCRIBE_INSTANCES = "DescribeInstances"
ACTION_DESCRIBE_INSTANCES_WITH_MONITORS = "DescribeInstancesWithMonitors"
ACTION_RUN_INSTANCES = "RunInstances"
ACTION_CLONE_INSTANCES = "CloneInstances"
ACTION_TERMINATE_INSTANCES = "TerminateInstances"
ACTION_START_INSTANCES = "StartInstances"
ACTION_RESTART_INSTANCES = "RestartInstances"
ACTION_STOP_INSTANCES = "StopInstances"
ACTION_RESIZE_INSTANCES = "ResizeInstances"
ACTION_RESET_INSTANCES = "ResetInstances"
ACTION_MODIFY_INSTANCE_ATTRIBUTES = "ModifyInstanceAttributes"
ACTION_CREATE_BROKERS = "CreateBrokers"
ACTION_DELETE_BROKERS = "DeleteBrokers"
ACTION_LEASE = "Lease"

# volumes
ACTION_DESCRIBE_VOLUMES = "DescribeVolumes"
ACTION_CREATE_VOLUMES = "CreateVolumes"
ACTION_DELETE_VOLUMES = "DeleteVolumes"
ACTION_ATTACH_VOLUMES = "AttachVolumes"
ACTION_DETACH_VOLUMES = "DetachVolumes"
ACTION_RESIZE_VOLUMES = "ResizeVolumes"
ACTION_MODIFY_VOLUME_ATTRIBUTES = "ModifyVolumeAttributes"

# security group
ACTION_DESCRIBE_SECURITY_GROUPS = "DescribeSecurityGroups"
ACTION_CREATE_SECURITY_GROUP = "CreateSecurityGroup"
ACTION_MODIFY_SECURITY_GROUP_ATTRIBUTES = "ModifySecurityGroupAttributes"
ACTION_DELETE_SECURITY_GROUPS = "DeleteSecurityGroups"
ACTION_APPLY_SECURITY_GROUP = "ApplySecurityGroup"
ACTION_REMOVE_SECURITY_GROUP = "RemoveSecurityGroup"
ACTION_ROLLBACK_SECURITY_GROUP = "RollbackSecurityGroup"

ACTION_DESCRIBE_SECURITY_GROUP_RULES = "DescribeSecurityGroupRules"
ACTION_ADD_SECURITY_GROUP_RULES = "AddSecurityGroupRules"
ACTION_DELETE_SECURITY_GROUP_RULES = "DeleteSecurityGroupRules"
ACTION_MODIFY_SECURITY_GROUP_RULE_ATTRIBUTES = "ModifySecurityGroupRuleAttributes"

ACTION_DESCRIBE_SECURITY_GROUP_IPSETS = "DescribeSecurityGroupIPSets"
ACTION_CREATE_SECURITY_GROUP_IPSET = "CreateSecurityGroupIPSet"
ACTION_DELETE_SECURITY_GROUP_IPSETS = "DeleteSecurityGroupIPSets"
ACTION_MODIFY_SECURITY_GROUP_IPSET_ATTRIBUTES = "ModifySecurityGroupIPSetAttributes"
ACTION_APPLY_SECURITY_GROUP_IPSETS = "ApplySecurityGroupIPSets"

ACTION_APPLY_SECURITY_GROUP_RULESET = "ApplySecurityGroupRuleSet"
ACTION_DESCRIBE_SECURITY_GROUP_AND_RULESET = "DescribeSecurityGroupAndRuleSet"
ACTION_ADD_SECURITY_GROUP_RULESETS = "AddSecurityGroupRuleSets"
ACTION_REMOVE_SECURITY_GROUP_RULESETS = "RemoveSecurityGroupRuleSets"

ACTION_DESCRIBE_SECURITY_GROUP_SNAPSHOTS = "DescribeSecurityGroupSnapshots"
ACTION_CREATE_SECURITY_GROUP_SNAPSHOT = "CreateSecurityGroupSnapshot"
ACTION_DELETE_SECURITY_GROUP_SNAPSHOTS = "DeleteSecurityGroupSnapshots"

# vxnets
ACTION_DESCRIBE_VXNETS = "DescribeVxnets"
ACTION_CREATE_VXNETS = "CreateVxnets"
ACTION_DELETE_VXNETS = "DeleteVxnets"
ACTION_JOIN_VXNET = "JoinVxnet"
ACTION_LEAVE_VXNET = "LeaveVxnet"
ACTION_MODIFY_VXNET_ATTRIBUTES = "ModifyVxnetAttributes"
ACTION_DESCRIBE_VXNET_INSTANCES = "DescribeVxnetInstances"
ACTION_DESCRIBE_VXNET_RESOURCES = "DescribeVxnetResources"
# router
ACTION_CREATE_ROUTERS = "CreateRouters"
ACTION_UPDATE_ROUTERS = "UpdateRouters"
ACTION_DELETE_ROUTERS = "DeleteRouters"
ACTION_JOIN_ROUTER = "JoinRouter"
ACTION_LEAVE_ROUTER = "LeaveRouter"
ACTION_DESCRIBE_ROUTERS = "DescribeRouters"
ACTION_DESCRIBE_ROUTER_VXNETS = "DescribeRouterVxnets"
ACTION_MODIFY_ROUTER_ATTRIBUTES = "ModifyRouterAttributes"
# monitor
ACTION_GET_MONITOR = "GetMonitor"
# vdi
ACTION_SEND_VDI_GUEST_MESSAGE = "SendVdiGuestMessage"
ACTION_SEND_VDI_GUEST_KEYS = "SendVdiGuestKeys"
# nics
ACTION_DESCRIBE_NICS = "DescribeNics"
ACTION_CREATE_NICS = "CreateNics"
ACTION_DELETE_NICS = "DeleteNics"
ACTION_MODIFY_NIC_ATTRIBUTES = "ModifyNicAttributes"
ACTION_ATTACH_NICS = "AttachNics"
ACTION_DETACH_NICS = "DetachNics"

# zone config
ACTION_DESCRIBE_ZONES = "DescribeZones"
ACTION_GET_RESOURCE_LIMIT = "GetResourceLimit"
ACTION_DESCRIBE_PLACE_GROUPS = "DescribePlaceGroups"

# ssh keypair
ACTION_DESCRIBE_SSH_KEY_PAIRS = "DescribeKeyPairs"
ACTION_CREATE_SSH_KEY_PAIR = "CreateKeyPair"

# Access Key
ACTION_DESCRIBE_ACCESS_KEYS = "DescribeAccessKeys"

# Access user
ACTION_DESCRIBE_USERS = "DescribeUsers"

#snapshot
ACTION_CREATE_SNAPSHOTS = "CreateSnapshots"
ACTION_DELETE_SNAPSHOTS = "DeleteSnapshots"
ACTION_APPLY_SNAPSHOTS = "ApplySnapshots"
ACTION_DESCRIBE_SNAPSHOTS = "DescribeSnapshots"
ACTION_MODIFY_SNAPSHOT_ATTRIBUTES = "ModifySnapshotAttributes"
ACTION_CAPTURE_INSTANCE_FROM_SNAPSHOT = "CaptureInstanceFromSnapshot"
ACTION_CREATE_VOLUME_FROM_SNAPSHOT = "CreateVolumeFromSnapshot"

# desktop_service_management
ACTION_MODIFY_RDB_ATTRIBUTES = "ModifyRDBAttributes"
ACTION_MODIFY_CACHE_ATTRIBUTES = "ModifyCacheAttributes"
ACTION_MODIFY_S2SERVER_ATTRIBUTES = "ModifyS2ServerAttributes"
ACTION_MODIFY_LOADBALANCER_ATTRIBUTES = "ModifyLoadBalancerAttributes"
ACTION_DESCRIBE_RDBS = "DescribeRDBs"
ACTION_DESCRIBE_CLUSTERS = "DescribeClusters"
ACTION_DESCRIBE_CACHES = "DescribeCaches"
ACTION_DESCRIBE_LOADBALANCERS = "DescribeLoadBalancers"
ACTION_DESCRIBE_LOADBALANCER_BACKENDS = "DescribeLoadBalancerBackends"
ACTION_DESCRIBE_S2SERVERS = "DescribeS2Servers"
ACTION_MODIFY_CLUSTER_ATTRIBUTES = "ModifyClusterAttributes"

ACTION_DESCRIBE_S2_GROUPS = "DescribeS2Groups"
ACTION_CREATE_S2_ACCOUNT = "CreateS2Account"
ACTION_DESCRIBE_S2_ACCOUNTS = "DescribeS2Accounts"
ACTION_UPDATE_S2_SERVERS = "UpdateS2Servers"
ACTION_CREATE_S2_SERVER = "CreateS2Server"
ACTION_CREATE_S2_SHARED_TARGET = "CreateS2SharedTarget"
ACTION_POWEROFF_S2_SERVERS = "PowerOffS2Servers"
ACTION_POWERON_S2_SERVERS = "PowerOnS2Servers"

# tag
ACTION_DESCRIBE_TAGS = "DescribeTags"
ACTION_CREATE_TAG = "CreateTag"
ACTION_ATTACH_TAGS = "AttachTags"

# quotas
ACTION_GET_QUOTA_LEFT = "GetQuotaLeft"

SERACH_ACTIONS =[
    
    # instance
    ACTION_RUN_INSTANCES,
    ACTION_CLONE_INSTANCES,
    ACTION_TERMINATE_INSTANCES,
    ACTION_START_INSTANCES,
    ACTION_RESTART_INSTANCES,
    ACTION_STOP_INSTANCES,
    ACTION_RESIZE_INSTANCES,
    ACTION_RESET_INSTANCES,
    # volume
    ACTION_CREATE_VOLUMES,
    ACTION_DELETE_VOLUMES,
    ACTION_ATTACH_VOLUMES,
    ACTION_DETACH_VOLUMES,
    ACTION_RESIZE_VOLUMES,
    # vxnet
    ACTION_CREATE_VXNETS,
    ACTION_DELETE_VXNETS,
    ACTION_JOIN_VXNET,
    ACTION_LEAVE_VXNET,
    # nic
    ACTION_ATTACH_NICS,
    ACTION_DETACH_NICS,
    ACTION_CREATE_NICS,
    # image
    ACTION_CAPTURE_INSTANCE,
    ACTION_DELETE_IMAGES,
    
    # router
    ACTION_JOIN_ROUTER,
    ACTION_LEAVE_ROUTER,
    
    # snapshot
    ACTION_CREATE_SNAPSHOTS,
    ACTION_DELETE_SNAPSHOTS,
    ACTION_APPLY_SNAPSHOTS,
    ACTION_CAPTURE_INSTANCE_FROM_SNAPSHOT,
    ACTION_CREATE_VOLUME_FROM_SNAPSHOT
]
# job action
JOB_ACTIONS =[
    
    # instance
    ACTION_LEASE,
    ACTION_RUN_INSTANCES,
    ACTION_CLONE_INSTANCES,
    ACTION_TERMINATE_INSTANCES,
    ACTION_START_INSTANCES,
    ACTION_RESTART_INSTANCES,
    ACTION_STOP_INSTANCES,
    ACTION_RESIZE_INSTANCES,
    ACTION_RESET_INSTANCES,
    # volume
    ACTION_CREATE_VOLUMES,
    ACTION_DELETE_VOLUMES,
    ACTION_ATTACH_VOLUMES,
    ACTION_DETACH_VOLUMES,
    ACTION_RESIZE_VOLUMES,
    # vxnet
    ACTION_CREATE_VXNETS,
    ACTION_DELETE_VXNETS,
    ACTION_JOIN_VXNET,
    ACTION_LEAVE_VXNET,
    # nic
    ACTION_ATTACH_NICS,
    ACTION_DETACH_NICS,
    # image
    ACTION_CAPTURE_INSTANCE,
    ACTION_DELETE_IMAGES,
    
    # security
    ACTION_APPLY_SECURITY_GROUP,
    ACTION_REMOVE_SECURITY_GROUP,
    ACTION_APPLY_SECURITY_GROUP_IPSETS,
    
    # router
    ACTION_JOIN_ROUTER,
    ACTION_LEAVE_ROUTER,
    
    # snapshot
    ACTION_CREATE_SNAPSHOTS,
    ACTION_DELETE_SNAPSHOTS,
    ACTION_APPLY_SNAPSHOTS,
    ACTION_CAPTURE_INSTANCE_FROM_SNAPSHOT,
    ACTION_CREATE_VOLUME_FROM_SNAPSHOT,

    #s2
    ACTION_UPDATE_S2_SERVERS,
    ACTION_CREATE_S2_SERVER,
    ACTION_POWEROFF_S2_SERVERS,
    ACTION_POWERON_S2_SERVERS
]

DESCRIBE_ACTIONS =[
    ACTION_DESCRIBE_GPUS,
    ACTION_DESCRIBE_JOBS,
    ACTION_DESCRIBE_IMAGES,
    ACTION_DESCRIBE_INSTANCES,
    ACTION_DESCRIBE_INSTANCES_WITH_MONITORS,
    ACTION_CREATE_BROKERS,
    ACTION_DESCRIBE_VOLUMES,
    ACTION_DESCRIBE_SECURITY_GROUPS,
    ACTION_DESCRIBE_SECURITY_GROUP_RULES,
    ACTION_DESCRIBE_SECURITY_GROUP_IPSETS,
    ACTION_DESCRIBE_VXNETS,
    ACTION_DESCRIBE_VXNET_INSTANCES,
    ACTION_DESCRIBE_VXNET_RESOURCES,
    ACTION_DESCRIBE_ROUTERS,
    ACTION_DESCRIBE_ROUTER_VXNETS,
    ACTION_GET_MONITOR,
    ACTION_DESCRIBE_NICS,
    ACTION_DESCRIBE_SNAPSHOTS,
]

RETRY_CREATE = [
    ACTION_RUN_INSTANCES,
    ACTION_CLONE_INSTANCES,
    ACTION_CREATE_VOLUMES, 
    ACTION_CREATE_SNAPSHOTS,
    ACTION_CREATE_NICS
]

SEARCH_TYPE_NIC =[
    ACTION_CREATE_NICS
]

SEARCH_TYPE_INST = [
    ACTION_RUN_INSTANCES,
    ACTION_CLONE_INSTANCES,
    ACTION_TERMINATE_INSTANCES,
    ACTION_START_INSTANCES,
    ACTION_RESTART_INSTANCES,
    ACTION_STOP_INSTANCES,
    ACTION_RESIZE_INSTANCES,
    ACTION_RESET_INSTANCES,
]
SEARCH_TYPE_VOL = [
    ACTION_CREATE_VOLUMES,
    ACTION_DELETE_VOLUMES,
    ACTION_ATTACH_VOLUMES,
    ACTION_DETACH_VOLUMES,
    ACTION_RESIZE_VOLUMES,
]

SEARCH_TYPE_SNAPSHOT = [
    ACTION_CREATE_SNAPSHOTS,
    ACTION_DELETE_SNAPSHOTS,
    ACTION_APPLY_SNAPSHOTS,
    ACTION_CAPTURE_INSTANCE_FROM_SNAPSHOT,
    ACTION_CREATE_VOLUME_FROM_SNAPSHOT
]

SEARCH_TYPE_IMG = [
    ACTION_CAPTURE_INSTANCE,
    ACTION_DELETE_IMAGES,
]

NO_JOB_RES = "no_job"

RETRY_ACTIONS = [
    ACTION_TERMINATE_INSTANCES,
    ACTION_DELETE_VOLUMES,
    ACTION_RESIZE_VOLUMES,
    ACTION_DELETE_SNAPSHOTS
]

SEARCH_RES_INST_TYPE = "instance"
SEARCH_RES_VOLUME_TYPE = "volume"
SEARCH_RES_IMAGE_TYPE = "image"
SEARCH_RES_NIC_TYPE = "nic"
SEARCH_RES_SNAPSHOT_TYPE = "snapshot"

# resource job interval
JOB_INTERVAL_5S = 5
JOB_INTERVAL_3S = 3
JOB_INTERVAL_60S = 60
JOB_INTERVAL_20S = 20
# retry time
RES_ACTION_RETRIES = 3
RES_ACTION_RETRY_INTERVAL = 10
# job timeout
CHECK_JOB_INTERVAL = 3
WAIT_JOB_TIMEOUT = 1800
WAIT_JOB_TIMEOUT_3600 = 3600
WAIT_JOB_TIMEOUT_600 = 600
QC_RESOURCE_JOB_LOCK='qc_resource_job'

