
from constants import (
    CHANNEL_API,
    CHANNEL_SESSION,
    CHANNEL_INTERNAL,
    CHECK_PLATFROM,
    ALL_PLATFORMS,
    USER_ROLE_GLOBAL_ADMIN,

    # component upgrade
    ACTION_VDI_DESCRIBE_COMPONENT_VERSION,
    ACTION_VDI_UPDATE_COMPONENT_VERSION,
    ACTION_VDI_EXECUTE_COMPONENT_UPGRADE
)

from constants import (
    ADMIN_ROLES,
    ALL_ROLES
)

COMPONENT_VSERION_API_ACL = {
            ACTION_VDI_DESCRIBE_COMPONENT_VERSION: {
                    CHANNEL_API: ALL_ROLES,
                    CHANNEL_SESSION: ALL_ROLES,
                    CHANNEL_INTERNAL: ALL_ROLES,
                    CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_UPDATE_COMPONENT_VERSION: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_EXECUTE_COMPONENT_UPGRADE: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            }
        }