
from constants import (
    CHANNEL_API,
    CHANNEL_SESSION,
    CHANNEL_INTERNAL,
    CHECK_PLATFROM,
    ALL_PLATFORMS,
    USER_ROLE_GLOBAL_ADMIN,
    ADMIN_ROLES,

    # snapshot
    ACTION_VDI_DESCRIBE_DESKTOP_SNAPSHOTS,
    ACTION_VDI_CREATE_DESKTOP_SNAPSHOTS,
    ACTION_VDI_MODIFY_DESKTOP_SNAPSHOT_ATTRIBUTES,
    ACTION_VDI_DELETE_DESKTOP_SNAPSHOTS,
    ACTION_VDI_APPLY_DESKTOP_SNAPSHOTS,
    ACTION_VDI_DESCRIBE_SNAPSHOT_GROUPS,
    ACTION_VDI_CREATE_SNAPSHOT_GROUP,
    ACTION_VDI_MODIFY_SNAPSHOT_GROUP,
    ACTION_VDI_DELETE_SNAPSHOT_GROUPS,
    ACTION_VDI_ADD_RESOURCE_TO_SNAPSHOT_GROUP,
    ACTION_VDI_DELETE_RESOURCE_FROM_SNAPSHOT_GROUP,
    ACTION_VDI_DESCRIBE_SNAPSHOT_GROUP_SNAPSHOTS,
)

SNAPSHOT_API_ACL = {
            ACTION_VDI_DESCRIBE_DESKTOP_SNAPSHOTS: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
            ACTION_VDI_CREATE_DESKTOP_SNAPSHOTS: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
            ACTION_VDI_MODIFY_DESKTOP_SNAPSHOT_ATTRIBUTES: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
            ACTION_VDI_DELETE_DESKTOP_SNAPSHOTS: {
                  CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                  CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                  CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
            ACTION_VDI_APPLY_DESKTOP_SNAPSHOTS: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
            ACTION_VDI_DESCRIBE_SNAPSHOT_GROUPS: {
                  CHANNEL_API: ADMIN_ROLES,
                  CHANNEL_SESSION: ADMIN_ROLES,
                  CHANNEL_INTERNAL: ADMIN_ROLES,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
            ACTION_VDI_CREATE_SNAPSHOT_GROUP: {
                  CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                  CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                  CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                  CHECK_PLATFROM: ALL_PLATFORMS
               },
            ACTION_VDI_MODIFY_SNAPSHOT_GROUP: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_DELETE_SNAPSHOT_GROUPS: {
                CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
                CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_ADD_RESOURCE_TO_SNAPSHOT_GROUP: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_DELETE_RESOURCE_FROM_SNAPSHOT_GROUP: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
            ACTION_VDI_DESCRIBE_SNAPSHOT_GROUP_SNAPSHOTS: {
                CHANNEL_API: ADMIN_ROLES,
                CHANNEL_SESSION: ADMIN_ROLES,
                CHANNEL_INTERNAL: ADMIN_ROLES,
                CHECK_PLATFROM: ALL_PLATFORMS
            },
              }