
from constants import (
    CHANNEL_API,
    CHANNEL_SESSION,
    CHANNEL_INTERNAL,
    CHECK_PLATFROM,
    ALL_PLATFORMS,
    USER_ROLE_GLOBAL_ADMIN,

    # desktop_service_management
    ACTION_VDI_DESCRIBE_DESKTOP_SERVICE_MANAGEMENTS,
    ACTION_VDI_MODIFY_DESKTOP_SERVICE_MANAGEMENT_ATTRIBUTES,
    ACTION_VDI_REFRESH_DESKTOP_SERVICE_MANAGEMENT,
    ACTION_VDI_DESCRIBE_DESKTOP_SERVICE_INSTANCES,
    ACTION_VDI_LOAD_DESKTOP_SERVICE_INSTANCES,
    ACTION_VDI_REMOVE_DESKTOP_SERVICE_INSTANCES
)

from constants import (
    ADMIN_ROLES,
    ALL_ROLES
)

DESKTOP_SERVICE_MANAGEMENT_API_ACL = {
        ACTION_VDI_DESCRIBE_DESKTOP_SERVICE_MANAGEMENTS: {
            CHANNEL_API: ADMIN_ROLES,
            CHANNEL_SESSION: ADMIN_ROLES,
            CHANNEL_INTERNAL: ADMIN_ROLES,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_MODIFY_DESKTOP_SERVICE_MANAGEMENT_ATTRIBUTES: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
        },
        ACTION_VDI_REFRESH_DESKTOP_SERVICE_MANAGEMENT: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
        },
        ACTION_VDI_DESCRIBE_DESKTOP_SERVICE_INSTANCES: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
        },
        ACTION_VDI_LOAD_DESKTOP_SERVICE_INSTANCES: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
        },
        ACTION_VDI_REMOVE_DESKTOP_SERVICE_INSTANCES: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
     }
    }