
from constants import (
    CHANNEL_API,
    CHANNEL_SESSION,
    CHANNEL_INTERNAL,
    CHECK_PLATFROM,
    ALL_PLATFORMS,
    USER_ROLE_GLOBAL_ADMIN,

    # apply group
    ACTION_VDI_CREATE_RESOURCE_APPLY_GROUP,
    ACTION_VDI_MODIFY_RESOURCE_APPLY_GROUP,
    ACTION_VDI_DESCRIBE_RESOURCE_APPLY_GROUPS,
    ACTION_VDI_DELETE_RESOURCE_APPLY_GROUPS,
    ACTION_VDI_INSERT_USER_TO_APPLY_GROUP,
    ACTION_VDI_REMOVE_USER_FROM_APPLY_GROUP,
    ACTION_VDI_INSERT_RESOURCE_TO_APPLY_GROUP,
    ACTION_VDI_REMOVE_RESOURCE_FROM_APPLY_GROUP,

    # approve group
    ACTION_VDI_CREATE_RESOURCE_APPROVE_GROUP,
    ACTION_VDI_MODIFY_RESOURCE_APPROVE_GROUP,
    ACTION_VDI_DESCRIBE_RESOURCE_APPROVE_GROUPS,
    ACTION_VDI_DELETE_RESOURCE_APPROVE_GROUPS,
    ACTION_VDI_INSERT_USER_TO_APPROVE_GROUP,
    ACTION_VDI_REMOVE_USER_FROM_APPROVE_GROUP,
    ACTION_VDI_MAP_APPLY_GROUP_AND_APPROVE_GROUP,
    ACTION_VDI_UNMAP_APPLY_GROUP_AND_APPROVE_GROUP,

    # apply form
    ACTION_VDI_CREATE_DESKTOP_APPLY_FORM,
    ACTION_VDI_DESCRIBE_DESKTOP_APPLY_FORMS,
    ACTION_VDI_MODIFY_DESKTOP_APPLY_FORM,
    ACTION_VDI_DELETE_DESKTOP_APPLY_FORMS,
    ACTION_VDI_DEAL_DESKTOP_APPLY_FORM,
    ACTION_VDI_GET_APPROVE_USERS,
)

from constants import (
    ADMIN_ROLES,
    ALL_ROLES
)

APPLY_APPROVE_API_ACL = {
        ACTION_VDI_CREATE_RESOURCE_APPLY_GROUP: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_MODIFY_RESOURCE_APPLY_GROUP: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_DESCRIBE_RESOURCE_APPLY_GROUPS: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_DELETE_RESOURCE_APPLY_GROUPS: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_INSERT_USER_TO_APPLY_GROUP: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
             },
        ACTION_VDI_REMOVE_USER_FROM_APPLY_GROUP: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_INSERT_RESOURCE_TO_APPLY_GROUP: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_REMOVE_RESOURCE_FROM_APPLY_GROUP: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_CREATE_RESOURCE_APPROVE_GROUP: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_MODIFY_RESOURCE_APPROVE_GROUP: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_DESCRIBE_RESOURCE_APPROVE_GROUPS: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_DELETE_RESOURCE_APPROVE_GROUPS: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_INSERT_USER_TO_APPROVE_GROUP: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_REMOVE_USER_FROM_APPROVE_GROUP: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_MAP_APPLY_GROUP_AND_APPROVE_GROUP: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_UNMAP_APPLY_GROUP_AND_APPROVE_GROUP: {
            CHANNEL_API: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_SESSION: USER_ROLE_GLOBAL_ADMIN,
            CHANNEL_INTERNAL: USER_ROLE_GLOBAL_ADMIN,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_CREATE_DESKTOP_APPLY_FORM: {
            CHANNEL_API: ALL_ROLES,
            CHANNEL_SESSION: ALL_ROLES,
            CHANNEL_INTERNAL: ALL_ROLES,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_DESCRIBE_DESKTOP_APPLY_FORMS: {
            CHANNEL_API: ALL_ROLES,
            CHANNEL_SESSION: ALL_ROLES,
            CHANNEL_INTERNAL: ALL_ROLES,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_MODIFY_DESKTOP_APPLY_FORM: {
            CHANNEL_API: ALL_ROLES,
            CHANNEL_SESSION: ALL_ROLES,
            CHANNEL_INTERNAL: ALL_ROLES,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_DELETE_DESKTOP_APPLY_FORMS: {
            CHANNEL_API: ALL_ROLES,
            CHANNEL_SESSION: ALL_ROLES,
            CHANNEL_INTERNAL: ALL_ROLES,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_DEAL_DESKTOP_APPLY_FORM: {
            CHANNEL_API: ALL_ROLES,
            CHANNEL_SESSION: ALL_ROLES,
            CHANNEL_INTERNAL: ALL_ROLES,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        ACTION_VDI_GET_APPROVE_USERS: {
            CHANNEL_API: ALL_ROLES,
            CHANNEL_SESSION: ALL_ROLES,
            CHANNEL_INTERNAL: ALL_ROLES,
            CHECK_PLATFROM: ALL_PLATFORMS
            },
        }